#### add method call
POST http://localhost:9191/SOAPLab0301/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope 
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    >

    <soap:Body>
        <jets:AddToNums xmlns:jets="myTargetNameSpace">
            <arg0>2</arg0>
            <arg1>4</arg1>
        </jets:AddToNums>
    </soap:Body>

</soap:Envelope>


### test status method call 
POST http://localhost:9191/SOAPLab0301/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope 
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    
    <soap:Body>
        <jets:testStatus xmlns:jets="http://webservices.arabie.com/">
            <arg0 xsi:type="xsd:int">33</arg0>
        </jets:testStatus>
    </soap:Body>

</soap:Envelope>

### test status method call 
POST http://localhost:9191/SOAPLab0301/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope 
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    >
    
    <soap:Body>
        <jets:testStatus xmlns:jets="myTargetNameSpace">
            <arg0>33</arg0>
        </jets:testStatus>
    </soap:Body>

</soap:Envelope>
### test echo method call 
POST http://localhost:9191/SOAPLab0301/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope 
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    >
    # <soap:Header>
    #     <jets:echo xmlns:jets="myTargetNameSpace">
    #         <myParamName>33</myParamName>
    #     </jets:echo>
    # </soap:Header>
    <soap:Body>
        <jets:echo xmlns:jets="myTargetNameSpace">
            <myParamName>33</myParamName>
        </jets:echo>
    </soap:Body>

</soap:Envelope>


###
# ERROR -> what is even "jets" prefix mean !?
POST http://localhost:9595/SOAP-D1/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    
    <soap:Body>
        <jets:add>
            <arg0>33</arg0>
            <arg1>33</arg1>
        </jets:add>
    </soap:Body>

</soap:Envelope>

###
# ERROR -> No way to find out where is this add method
POST http://localhost:9595/SOAP-D1/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    
    <soap:Body>
        <add>
            <arg0>33</arg0>
            <arg1>33</arg1>
        </add>
    </soap:Body>

</soap:Envelope>



###
# SOAP Fault - Division by zero (Runtime Exception)
POST http://localhost:9595/SOAP-D1/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://jets.iti.gov.eg/">
    
    <soap:Body>
        <jets:div>
            <arg0>12</arg0>
            <arg1>0</arg1>
        </jets:div>
    </soap:Body>

</soap:Envelope>
