##### insert book request 
POST http://localhost:9191/SOAPLab0201/ws/book HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:bookService = "http://webservices.arabie.com/">
    
    <soap:Body>
        <bookService:addBook>
            <arg0>"aaaa"</arg0>
            <arg1>20</arg1>
            <arg2>12.5</arg2>
            <arg3>"aaaaa"</arg3>
        </bookService:addBook>
    </soap:Body>

</soap:Envelope>
####### select request

POST http://localhost:9191/SOAPLab0101/ws/book HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:bookService = "http://webservices.arabie.com/">
    
    <soap:Body>
        <bookService:getBook>
            <arg0>6</arg0>
        </bookService:getBook>
    </soap:Body>

</soap:Envelope>

### delete request
POST http://localhost:9191/SOAPLab0101/ws/book HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:bookService = "http://webservices.arabie.com/">
    
    <soap:Body>
        <bookService:deleteBook>
            <arg0>8</arg0>
        </bookService:deleteBook>
    </soap:Body>

</soap:Envelope>
###  update book request
POST http://localhost:9191/SOAPLab0101/ws/book HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:bookService = "http://webservices.arabie.com/">
    
    <soap:Body>
        <bookService:updateBook>
            <arg0>6</arg0>
            <arg1>ahmed</arg1>
        </bookService:updateBook>
    </soap:Body>

</soap:Envelope>
###

POST http://localhost:9595/SOAP-D1/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    
    <soap:Body>
        <jets:add xmlns:jets="http://jets.iti.gov.eg/">
            <arg0>33</arg0>
            <arg1>33</arg1>
        </jets:add>
    </soap:Body>

</soap:Envelope>


###
# ERROR -> what is even "jets" prefix mean !?
POST http://localhost:9595/SOAP-D1/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    
    <soap:Body>
        <jets:add>
            <arg0>33</arg0>
            <arg1>33</arg1>
        </jets:add>
    </soap:Body>

</soap:Envelope>

###
# ERROR -> No way to find out where is this add method
POST http://localhost:9595/SOAP-D1/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    
    <soap:Body>
        <add>
            <arg0>33</arg0>
            <arg1>33</arg1>
        </add>
    </soap:Body>

</soap:Envelope>



###
# SOAP Fault - Division by zero (Runtime Exception)
POST http://localhost:9595/SOAP-D1/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://jets.iti.gov.eg/">
    
    <soap:Body>
        <jets:div>
            <arg0>12</arg0>
            <arg1>0</arg1>
        </jets:div>
    </soap:Body>

</soap:Envelope>
