
package com.arabie.myservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0-M2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookService", targetNamespace = "http://webservices.arabie.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBook", targetNamespace = "http://webservices.arabie.com/", className = "com.arabie.myservice.DeleteBook")
    @ResponseWrapper(localName = "deleteBookResponse", targetNamespace = "http://webservices.arabie.com/", className = "com.arabie.myservice.DeleteBookResponse")
    @Action(input = "http://webservices.arabie.com/BookService/deleteBookRequest", output = "http://webservices.arabie.com/BookService/deleteBookResponse")
    public boolean deleteBook(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.arabie.myservice.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBook", targetNamespace = "http://webservices.arabie.com/", className = "com.arabie.myservice.GetBook")
    @ResponseWrapper(localName = "getBookResponse", targetNamespace = "http://webservices.arabie.com/", className = "com.arabie.myservice.GetBookResponse")
    @Action(input = "http://webservices.arabie.com/BookService/getBookRequest", output = "http://webservices.arabie.com/BookService/getBookResponse")
    public Book getBook(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.arabie.myservice.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBook", targetNamespace = "http://webservices.arabie.com/", className = "com.arabie.myservice.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://webservices.arabie.com/", className = "com.arabie.myservice.AddBookResponse")
    @Action(input = "http://webservices.arabie.com/BookService/addBookRequest", output = "http://webservices.arabie.com/BookService/addBookResponse")
    public Book addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.arabie.myservice.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateBook", targetNamespace = "http://webservices.arabie.com/", className = "com.arabie.myservice.UpdateBook")
    @ResponseWrapper(localName = "updateBookResponse", targetNamespace = "http://webservices.arabie.com/", className = "com.arabie.myservice.UpdateBookResponse")
    @Action(input = "http://webservices.arabie.com/BookService/updateBookRequest", output = "http://webservices.arabie.com/BookService/updateBookResponse")
    public Book updateBook(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
